#!/bin/bash
# install_hooks.sh — reconstruct git safety hooks from a gitignored patterns file.
#
# The pre-commit and pre-push hooks contain PII and a real secret (the
# patterns they scan for), so they can't be committed. This script
# rebuilds them from .devin/hook-patterns.conf (gitignored, local-only).
#
# Run this after a fresh clone, or whenever the patterns file changes.
# Idempotent — safe to run repeatedly. Verified by scripts/devin_resume.sh.
#
# Usage: scripts/install_hooks.sh
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(cd "$(dirname "$0")/.." && pwd)")"
PATTERNS_FILE="$REPO_ROOT/.devin/hook-patterns.conf"
HOOKS_DIR="$REPO_ROOT/.git/hooks"

if [[ ! -f "$PATTERNS_FILE" ]]; then
    echo "ERROR: Patterns file not found: $PATTERNS_FILE"
    echo "  This file is gitignored (contains PII). If this is a fresh clone,"
    echo "  ask the product owner to provide it, or recreate it from the patterns"
    echo "  documented in .git/hooks/pre-push (if the old hooks still exist)."
    exit 1
fi

if [[ ! -d "$HOOKS_DIR" ]]; then
    mkdir -p "$HOOKS_DIR"
fi

# --- Parse patterns file into arrays ---
PII_PATTERNS=()
SENSITIVE_FILE_PATTERNS=()
BLOCKED_BRANCH_PREFIXES=()
BLOCKED_BRANCH_NAMES=()

while IFS= read -r line; do
    # Skip comments and blank lines
    [[ "$line" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${line// }" ]] && continue

    tag="${line%% *}"
    value="${line#* }"

    case "$tag" in
        "[pii]")                    PII_PATTERNS+=("$value") ;;
        "[sensitive-file]")         SENSITIVE_FILE_PATTERNS+=("$value") ;;
        "[blocked-branch-prefix]")  BLOCKED_BRANCH_PREFIXES+=("$value") ;;
        "[blocked-branch]")         BLOCKED_BRANCH_NAMES+=("$value") ;;
    esac
done < "$PATTERNS_FILE"

# --- Helper: write a bash array literal into a script ---
write_array() {
    local name="$1"
    shift
    local arr=("$@")
    echo "$name=("
    for item in "${arr[@]}"; do
        echo "    \"$item\""
    done
    echo ")"
}

# --- Generate pre-commit hook ---
PRE_COMMIT="$HOOKS_DIR/pre-commit"
cat > "$PRE_COMMIT" << 'PRE_COMMIT_HEADER'
#!/bin/bash
# Pre-commit hook: blocks committing personal data or sensitive files.
#
# AUTO-GENERATED by scripts/install_hooks.sh — do not edit directly.
# Edit .devin/hook-patterns.conf and re-run scripts/install_hooks.sh.
#
# This is the first gate — it stops PII from entering git history at all.
# The pre-push hook is the second gate (in case this hook is bypassed
# or a re-clone lacks it). Together they form defense in depth:
#
#   pre-commit  →  PII never enters a local commit
#   pre-push    →  PII never reaches a remote (catches re-clone gaps)
#
# This hook scans ONLY staged added lines (not full file content), so
# editing a file that already contains PII elsewhere won't trigger a
# false positive. Deletions are always allowed.
#
# To bypass (NOT RECOMMENDED): git commit --no-verify

set -euo pipefail

PRE_COMMIT_HEADER

# Write the arrays
write_array "PII_PATTERNS" "${PII_PATTERNS[@]}" >> "$PRE_COMMIT"
echo "" >> "$PRE_COMMIT"
write_array "SENSITIVE_FILE_PATTERNS" "${SENSITIVE_FILE_PATTERNS[@]}" >> "$PRE_COMMIT"

cat >> "$PRE_COMMIT" << 'PRE_COMMIT_BODY'

# --- Get staged files (added or modified only; deletions are fine) ---
staged_files=$(git diff --cached --name-only --diff-filter=AM)

if [[ -z "$staged_files" ]]; then
    exit 0
fi

blocked=0

for file in $staged_files; do
    # --- Check 1: Sensitive file patterns ---
    for sensitive_pattern in "${SENSITIVE_FILE_PATTERNS[@]}"; do
        # shellcheck disable=SC2254
        case "$file" in
            $sensitive_pattern)
                echo ""
                echo "BLOCKED: Staged file '$file' matches sensitive pattern: '$sensitive_pattern'"
                echo "  This file must not be committed to the repo."
                echo ""
                echo "  To override (DANGEROUS): git commit --no-verify"
                echo ""
                blocked=1
                ;;
        esac
    done

    # --- Check 2: PII patterns in staged added lines ---
    added_lines=$(git diff --cached -U0 -- "$file" 2>/dev/null | grep -E '^\+[^+]' || true)

    if [[ -n "$added_lines" ]]; then
        for pattern in "${PII_PATTERNS[@]}"; do
            if echo "$added_lines" | grep -qF "$pattern"; then
                echo ""
                echo "BLOCKED: Staged content in '$file' contains PII pattern: '$pattern'"
                echo ""
                echo "  Added lines matching the pattern:"
                echo "$added_lines" | grep -F "$pattern" | head -5 | sed 's/^/    /'
                echo ""
                echo "  Remove the PII before committing."
                echo ""
                echo "  To override (DANGEROUS): git commit --no-verify"
                echo ""
                blocked=1
                break
            fi
        done
    fi
done

if [[ $blocked -ne 0 ]]; then
    exit 1
fi

exit 0
PRE_COMMIT_BODY

chmod +x "$PRE_COMMIT"

# --- Generate pre-push hook ---
PRE_PUSH="$HOOKS_DIR/pre-push"
cat > "$PRE_PUSH" << 'PRE_PUSH_HEADER'
#!/bin/bash
# Pre-push hook: blocks pushing branches that contain personal data
# or sensitive documents.
#
# AUTO-GENERATED by scripts/install_hooks.sh — do not edit directly.
# Edit .devin/hook-patterns.conf and re-run scripts/install_hooks.sh.
#
# This is the hard gate. Even if someone runs `git push --all` or
# explicitly pushes archive/pre-squash, this hook will reject it.
#
# The hook checks:
#   1. The branch being pushed is not in a blocklist (archive/*, dev, pre-rebrand)
#   2. The commits being pushed don't contain known PII patterns
#   3. The commits being pushed don't add sensitive files (patent docs, .env, keys)
#
# To bypass (NOT RECOMMENDED): git push --no-verify

set -euo pipefail

PRE_PUSH_HEADER

write_array "BLOCKED_BRANCH_PREFIXES" "${BLOCKED_BRANCH_PREFIXES[@]}" >> "$PRE_PUSH"
echo "" >> "$PRE_PUSH"
write_array "BLOCKED_BRANCH_NAMES" "${BLOCKED_BRANCH_NAMES[@]}" >> "$PRE_PUSH"
echo "" >> "$PRE_PUSH"
write_array "PII_PATTERNS" "${PII_PATTERNS[@]}" >> "$PRE_PUSH"
echo "" >> "$PRE_PUSH"
write_array "SENSITIVE_FILE_PATTERNS" "${SENSITIVE_FILE_PATTERNS[@]}" >> "$PRE_PUSH"

cat >> "$PRE_PUSH" << 'PRE_PUSH_BODY'

# Read stdin: lines of "<local-ref> <local-sha> <remote-ref> <remote-sha>"
while read -r local_ref local_sha remote_ref remote_sha; do
    if [[ "$local_sha" =~ ^0+$ ]]; then
        continue
    fi

    branch_name="${local_ref#refs/heads/}"

    for prefix in "${BLOCKED_BRANCH_PREFIXES[@]}"; do
        if [[ "$branch_name" == "${prefix}"* ]]; then
            echo ""
            echo "BLOCKED: Branch '$branch_name' is on the blocklist."
            echo "  It contains pre-squash history with personal data."
            echo "  If you need to push history, squash first (see .devin/SLICE_LOG.md)."
            echo ""
            echo "  To override (DANGEROUS): git push --no-verify"
            echo ""
            exit 1
        fi
    done

    for blocked in "${BLOCKED_BRANCH_NAMES[@]}"; do
        if [[ "$branch_name" == "$blocked" ]]; then
            echo ""
            echo "BLOCKED: Branch '$branch_name' is on the blocklist."
            echo "  It contains pre-squash history with personal data."
            echo ""
            echo "  To override (DANGEROUS): git push --no-verify"
            echo ""
            exit 1
        fi
    done

    if [[ "$remote_sha" =~ ^0+$ ]]; then
        commits=$(git rev-list "$local_sha" --not --remotes 2>/dev/null)
    else
        commits=$(git rev-list "${remote_sha}..${local_sha}" 2>/dev/null)
    fi

    for commit in $commits; do
        for pattern in "${PII_PATTERNS[@]}"; do
            if git grep -l "$pattern" "$commit" -- . ':(exclude).git/hooks/*' 2>/dev/null | grep -v "^${commit}:.git/hooks/" | grep -q .; then
                echo ""
                echo "BLOCKED: Commit $commit contains PII pattern: '$pattern'"
                echo "  Files containing the pattern:"
                git grep -l "$pattern" "$commit" -- . ':(exclude).git/hooks/*' 2>/dev/null | grep -v "^${commit}:.git/hooks/" | head -10 | sed 's/^/    /'
                echo ""
                echo "  This commit must not be pushed. Squash or fix the PII first."
                echo ""
                echo "  To override (DANGEROUS): git push --no-verify"
                echo ""
                exit 1
            fi
        done

        files_in_commit=$(git diff-tree --no-commit-id --name-only -r --diff-filter=AM "$commit" 2>/dev/null)
        for file in $files_in_commit; do
            for sensitive_pattern in "${SENSITIVE_FILE_PATTERNS[@]}"; do
                # shellcheck disable=SC2254
                case "$file" in
                    $sensitive_pattern)
                        echo ""
                        echo "BLOCKED: Commit $commit adds sensitive file: '$file'"
                        echo "  Pattern matched: '$sensitive_pattern'"
                        echo "  This file must not be in the public repo."
                        echo ""
                        echo "  To override (DANGEROUS): git push --no-verify"
                        echo ""
                        exit 1
                        ;;
                esac
            done
        done
    done

    echo "  OK: $branch_name — no blocked branches, no PII detected"
done

exit 0
PRE_PUSH_BODY

chmod +x "$PRE_PUSH"

echo "Installed:"
echo "  $PRE_COMMIT"
echo "  $PRE_PUSH"
echo "Patterns from: $PATTERNS_FILE"
